### ISSUE TITLE
Doesn't work on my computer

### ISSUE THREAD

**Issue by wesbos** [r3volution11/Cobalt2-Flat-Theme#1]
Tried to install this a few times but every time I add:

```
"theme": "cobalt2-flat-theme.sublime-theme",
```

I don't get any errors, but everything is just black. 

Does it have something to do with the case?

**Comment by Drixled** [comment]
Same problem here o/

I have the following error:   
![screen shot 2016-08-10 at 10 15 28](https://cloud.githubusercontent.com/assets/1701402/17559328/81e1baa8-5ee3-11e6-9105-4d0c5d3455fe.jpg)

**Comment by glaszczyk** [comment]
I solved this problem installing both Cobalt2 and Cobalt Flat themes. 
My User settings file looks like that:
```
{
"color_scheme": "Packages/Cobalt2 Flat Theme/cobalt2.tmTheme",
"color_scheme": "Packages/Theme - Cobalt2/cobalt2.tmTheme",
}
```

It works for me.

**Comment by r3volution11** [comment]
Sorry for the delay in getting this fixed. In progress!

**Comment by r3volution11** [comment]
@wesbos If you set the theme name as "Cobalt2-Flat-Theme.sublime-theme" does it work correctly?

**Comment by r3volution11** [comment]
This should be working now with the latest release. The theme name is case sensitive.

**Comment by dfridline** [comment]
Having problems getting the theme to load properly.  I set the theme name with
`"Cobalt-Flat-Theme.sublime-theme"` but I get some really wild coloring afterwards on the tabs and folder icons. (Orange and red bands).
![image 2017-09-02 at 10 52 38 am](https://user-images.githubusercontent.com/30773958/29996474-27658f7a-8fcd-11e7-9e12-c85ecac73862.png)

**Comment by stormbringer94** [comment]
same here...
