### ISSUE TITLE
Icons not displaying properly and black sidebar window

### ISSUE THREAD

**Issue by arbolaez001** [r3volution11/cobalt2-flat-theme#2]
- For now I delete the `Cobalt2-flat-theme` file that is in the `/Sublime Text 3/Installed Packages` folder
- Download the theme folder from the repo and place it in the `Sublime Text 3/Packages` folder
- This seem to be working for me.

**Comment by wesbos** [comment]
Seems to be a problem with the install process

**Comment by r3volution11** [comment]
Sorry for the delay guys. Attempting to get this fixed. Hope to asap.

**Comment by xn4v8h** [comment]
Here's how I got it to work:

1. Delete `Cobalt2-flat-theme` file in `Installed Packages` folder
2. Download latest release
3. Copy downloaded folder to `Packages`, and renaming it to just: `cobalt2-flat-theme`
4. Making sure to use the capitalized version: `"theme": "Cobalt2-Flat-Theme.sublime-theme"`

**Comment by arbolaez001** [comment]
Cool @xn4v8h is working now! Thank you @wesbos @r3volution11 and @xn4v8h
