### ISSUE TITLE
Not able to see sidebar/tabs text

### ISSUE THREAD

**Issue by rkpatel33** [r3volution11/Cobalt2-Flat-Theme#4]
I see this in the sidebar and tabs row when I use the following settings. Any thoughts on what the issue might be? I have tried starting.

![image](https://cloud.githubusercontent.com/assets/3799489/19663414/e0b0f01a-9a09-11e6-87b4-634b71b4addb.png)

![image](https://cloud.githubusercontent.com/assets/3799489/19663397/cde6b528-9a09-11e6-8a61-9a93f4b9740d.png)

**Comment by r3volution11** [comment]
@rkpatel33 This should be working now with the latest release. The theme name is case sensitive.

**Comment by r3volution11** [comment]
@rkpatel33 Please grab the latest release and let me know if it works. Thanks!

**Comment by rkpatel33** [comment]
Ok thanks, will do.


_________________________
Rishi Patel | mail@rishinyc.com

On Fri, Jan 6, 2017 at 10:51 AM, Doug C. Hardester <notifications@github.com

**Comment by rkpatel33** [comment]
This is working now, thanks!


_________________________
Rishi Patel | mail@rishinyc.com

**Comment by r3volution11** [comment]
Thanks rkpatel33!
